package conan.ui.configuration;

import com.intellij.execution.Output;
import com.intellij.execution.OutputListener;
import com.intellij.execution.process.ProcessEvent;
import com.intellij.openapi.options.Configurable;
import com.intellij.ui.JBColor;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import conan.commands.ConfigInstall;
import conan.consistency.ConsistencyUtils;
import conan.utils.Utils;
import org.apache.commons.lang.StringUtils;
import org.jetbrains.annotations.Nls;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.swing.*;
import java.awt.*;

import static conan.consistency.Keys.CONFIG_INSTALL_URL;

/**
 * Represents the Conan settings form.
 *
 * Created by Yahav Itzhak on Feb 2018.
 */
public class ConanConfig implements Configurable, Configurable.NoScroll {

    public static final String CONFIG_NAME = "Conan";
    private JPanel rootPanel;
    private JTextField configInstallUrl;
    private JButton downloadConfiguration;
    private JLabel configInstallRes;

    @Nls
    @Override
    public String getDisplayName() {
        return CONFIG_NAME;
    }

    @Nullable
    @Override
    public JComponent createComponent() {
        downloadConfiguration.addActionListener(actionEvent -> {
            String url = configInstallUrl.getText();
            if (StringUtils.isBlank(url)) {
                url = ConsistencyUtils.getValue(CONFIG_INSTALL_URL);
            }
            ConsistencyUtils.setValue(CONFIG_INSTALL_URL, url);
            if (!Utils.validateUrl(url)) {
                setConfigInstallRes("Bad URL", false);
                return;
            }
            runConfigInstall(url);

        });
        return rootPanel;
    }

    /**
     * Run {@link ConfigInstall}.
     * @param url the url of the Conan configuration.
     */
    private void runConfigInstall(String url) {
        OutputListener processListener = new OutputListener() {
            @Override
            public void processTerminated(@NotNull ProcessEvent processEvent) {
                super.processTerminated(processEvent);
                Output configInstallOut = getOutput();
                if (configInstallOut.getExitCode() == 0) {
                    setConfigInstallRes("Success", true);
                } else {
                    setConfigInstallRes(Utils.getLastLine(configInstallOut.getStdout()), false);
                }
            }
        };
        new ConfigInstall(processListener, url).run();
    }

    private void setConfigInstallRes(String results, boolean isSuccess) {
        configInstallRes.setForeground(isSuccess ? JBColor.GREEN : JBColor.RED);
        configInstallRes.setText(results);
    }

    @Override
    public boolean isModified() {
        return true;
    }

    @Override
    public void reset() {
        configInstallUrl.setText(ConsistencyUtils.getValue(CONFIG_INSTALL_URL));
    }

    @Override
    public void apply() {
        ConsistencyUtils.setValue(CONFIG_INSTALL_URL, configInstallUrl.getText());
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Config install URL");
        rootPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        rootPanel.add(spacer1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        configInstallUrl = new JTextField();
        rootPanel.add(configInstallUrl, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        downloadConfiguration = new JButton();
        downloadConfiguration.setText("Download");
        rootPanel.add(downloadConfiguration, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        configInstallRes = new JLabel();
        configInstallRes.setText("");
        rootPanel.add(configInstallRes, new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
